name: PyTest

on:
  push:
    branches: ['**']  # Trigger on push to any branch
  pull_request:
    branches: ['**']

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen   # run Qt headless
      MPLBACKEND: Agg              # just in case matplotlib appears

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package + test deps
        run: |
          pip install -e ".[test]"
          # optional: linters too
          pip install -e ".[linters]"

      - name: Run tests with coverage
        run: |
          pytest --cov=parallax --cov-report=term-missing
        continue-on-error: true