name: PyTest

on:
  push:
    branches: ['**']  # Trigger on push to any branch
  pull_request:
    branches: ['**']

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen   # run Qt headless
      MPLBACKEND: Agg              # just in case matplotlib appears

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 libxkbcommon-x11-0

      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'

      - name: Install package + test deps
        run: uv sync --extra test --extra linters

      - name: Run tests with coverage
        run: uv run pytest --cov=parallax --cov-report=term-missing --cov-fail-under=30